import React from 'react';

export default function TermsAndConditions() {
  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-6">Terms & Conditions</h1>
      
      <div className="space-y-6">
        <section className="text-gray-700">
          <p className="mb-4">
            1. This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </p>
          
          <p className="mb-4">
            2. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name WWW.SILANYAS.COM (&apos;Website&apos;), including the related mobile site and mobile application (hereinafter referred to as &apos;Platform&apos;).
          </p>
          
          <p className="mb-4">
            3. The Platform is owned by Silanyas, a company incorporated under the Companies Act, 1956 with its registered office at Govind Puri, Kalkaji, New Delhi, India (hereinafter referred to as &apos;Platform Owner&apos;, &apos;we&apos;, &apos;us&apos;, &apos;our&apos;).
          </p>
          
          <p className="mb-4">
            4. Your use of the Platform and services and tools are governed by the following terms and conditions (&quot;Terms of Use&quot;) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference.
          </p>
          
          <p className="mb-4">
            5. For the purpose of these Terms of Use, wherever the context so requires &apos;you&apos;, &apos;your&apos; or &apos;user&apos; shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.
          </p>
          
          <p className="mb-4">
            6. ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
          </p>
          
          <div className="mt-6">
            <h2 className="text-2xl font-semibold mb-4">7. Use of Platform and Services</h2>
            <ul className="list-decimal ml-6 space-y-4">
              <li>To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.</li>
              <li>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services.</li>
              <li>Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner.</li>
              <li>The contents of the Platform and the Services are proprietary to us and are licensed to us.</li>
              <li>You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.</li>
              <li>You agree to pay us the charges associated with availing the Services.</li>
              <li>You agree not to use the Platform and/ or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.</li>
              <li>You agree and acknowledge that website and the Services may contain links to other third party websites.</li>
              <li>You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.</li>
            </ul>
          </div>
        </section>
      </div>
    </div>
  );
}
